service: serverless-nextjs-styled-components

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    nextConfigDir: "./"
    pageConfig:
      wp-page:
        events:
          - http:
              path: wp-page/{slug}
              request:
                parameters:
                  paths:
                    slug: true

package:
  exclude:
    - ./**
